version: 2.1
orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m pytest